substitutions:
  _BACKEND_ORIGIN: https://api.pdlawson.com

steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/paul-personal-306310/homepage-frontend || exit 0']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --cache-from=gcr.io/paul-personal-306310/homepage-frontend
      - -t=gcr.io/paul-personal-306310/homepage-frontend
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/paul-personal-306310/homepage-frontend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - homepage-frontend
      - --image=gcr.io/paul-personal-306310/homepage-frontend
      - --platform=managed
      - --region=europe-west1
      - --allow-unauthenticated
      - --set-env-vars=BACKEND_ORIGIN=${_BACKEND_ORIGIN}

images:
  - 'gcr.io/paul-personal-306310/homepage-frontend'
